Repository KTH-RPL/OpenSceneFlow, pull requests merged in 2025-03, with the labels that each got.

#3 Add rerun and open3d multi visualizer
  README.md
  dataprocess/README.md
  envprocess.yaml
  src/utils/__init__.py
  src/utils/eval_metric.py
  src/utils/mics.py
  src/utils/o3d_view.py
  tools/visualization.py
  tools/visualization_rerun.py
Labels: enhancement

#5 Fix scene flow ground truth generation in Argoverse 2
  Dockerfile
  README.md
  conf/save.yaml
  dataprocess/extract_av2.py
  environment.yaml
  src/models/__init__.py
  tools/visualization.py
Labels: question

#4 Merge SSF into codebase
  README.md
  assets/README.md
  assets/cuda/mmdet/__init__.py
  assets/cuda/mmdet/conv.py
  assets/cuda/mmdet/norm.py
  assets/cuda/mmdet/plugin.py
  assets/cuda/mmdet/resnet.py
  assets/cuda/mmdet/typing_utils.py
  conf/model/ssf.yaml
  dataprocess/README.md
  environment.yaml
  envsftool.yaml
  src/dataset.py
  src/models/__init__.py
  src/models/basic/decoder.py
  src/models/basic/encoder.py
  src/models/basic/flow4d_module.py
  src/models/basic/sparse_block.py
  src/models/basic/sparse_unet.py
  src/models/basic/spconv/__init__.py
  src/models/basic/spconv/overwrite_spconv/write_spconv2.py
  src/models/basic/ssf_module.py
  src/models/deflow.py
  src/models/fastflow3d.py
  src/models/ssf.py
  src/trainer.py
  src/utils/av2_eval.py
  src/utils/eval_metric.py
Labels: new method
